# Build for OpenCost fork

trigger: none

pr:
- main

variables:
  - group: lightops-pipeline


pool:
  vmImage: ubuntu-latest

steps:
# install go
- task: GoTool@0
  displayName: 'Download Go'
  inputs:
    version: '1.19.2'

- task: Go@0
  displayName: Install dependencies
  inputs:
    command: 'mod'
    arguments: 'tidy'
    workingDirectory: '$(Build.SourcesDirectory)'
 
# build opencost
- task: Go@0
  displayName: 'Build OpenCost'
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/costmodel'

# TODO needs to port-forward thanos query from a cluster to test
# kubectl -n lightops-obs-server port-forward service/thanos-query-frontend 34081:9090
# - task: Go@0
#   displayName: 'Run local tests'
#   inputs:
#     command: 'test'
#     arguments: '-timeout 700s'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/test'

